/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        safe:       { DEFAULT: '#22c55e', dark: '#16a34a' },
        suspicious: { DEFAULT: '#f59e0b', dark: '#d97706' },
        high:       { DEFAULT: '#f97316', dark: '#ea580c' },
        critical:   { DEFAULT: '#ef4444', dark: '#dc2626' },
        surface:    { 50: '#1a1a2e', 100: '#16213e', 200: '#0f3460', 300: '#533483' },
        base:       '#080810',
        
        "error-container": "#93000a",
        "primary-container": "#10b981",
        "surface-container-highest": "#31353f",
        "on-primary-fixed": "#002113",
        "secondary-container": "#a40217",
        "tertiary-fixed-dim": "#ffb690",
        "surface-container-high": "#262a34",
        "on-tertiary-fixed": "#341100",
        "secondary": "#ffb3ad",
        "tertiary-container": "#ff7e2d",
        "on-secondary-container": "#ffaea8",
        "surface-container-low": "#181b25",
        "on-background": "#dfe2ef",
        "on-primary-fixed-variant": "#005236",
        "on-error": "#690005",
        "surface-bright": "#353943",
        "on-primary": "#003824",
        "on-secondary-fixed-variant": "#930013",
        "tertiary-fixed": "#ffdbca",
        "inverse-surface": "#dfe2ef",
        "on-tertiary-fixed-variant": "#783200",
        "outline": "#86948a",
        "surface-container-lowest": "#0a0e17",
        "on-secondary-fixed": "#410004",
        "outline-variant": "#3c4a42",
        "inverse-primary": "#006c49",
        "surface": "#0f131c",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#6ffbbe",
        "on-secondary": "#68000a",
        "on-primary-container": "#00422b",
        "surface-variant": "#31353f",
        "secondary-fixed": "#ffdad7",
        "surface-dim": "#0f131c",
        "on-tertiary": "#552100",
        "on-surface": "#dfe2ef",
        "tertiary": "#ffb690",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#622700",
        "on-surface-variant": "#bbcabf",
        "primary": "#4edea3",
        "surface-tint": "#4edea3",
        "secondary-fixed-dim": "#ffb3ad",
        "background": "#0f131c",
        "inverse-on-surface": "#2c303a",
        "surface-container": "#1c1f29"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        display: ['"Orbitron"', 'monospace'],
        body:    ['"Inter"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
        headline: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      animation: {
        'pulse-slow':  'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'glow-red':    'glowRed 1.5s ease-in-out infinite alternate',
        'scan':        'scan 2s linear infinite',
        'float':       'float 6s ease-in-out infinite',
      },
      keyframes: {
        glowRed: {
          '0%':   { boxShadow: '0 0 5px #ef4444, 0 0 10px #ef4444' },
          '100%': { boxShadow: '0 0 20px #ef4444, 0 0 40px #ef4444, 0 0 60px #ef4444' },
        },
        scan: {
          '0%':   { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
}
